### ISSUE TITLE
NLP ressources

### ISSUE THREAD

**Issue by supersambo** [abdulqadir/linkssdgs#1]
Hi,
congratulations for winning this very tricky challenge and presenting your results in a beautiful and intuitive way! I was just wondering if the the source code of Natural Language part of this project is available somewhere. 

Thanks and best wishes!

**Comment by abdulqadir** [comment]
Hi,

The results were extracted using a Python script which queries an Apache Solr instance.

I was thinking of releasing the scripts along with a detailed post about the NLP part because the scripts on their own would not be very useful without the associated Synonyms list, etc.
